package com.esfimus.popularlibraries.mvp.presenter.repositories

import com.esfimus.popularlibraries.mvp.presenter.ListPresenterInterface
import com.esfimus.popularlibraries.mvp.view.repositories.RepositoryItemView

interface RepositoryListPresenterInterface : ListPresenterInterface<RepositoryItemView>